# nixos/config/system/agent-ops/credentials.nix
#
# How credentials reach the processes that are meant to have them, and nothing else.
#
# ── Where the switch lives, and why it is not here ──────────────────────────
# The one opt-in (`herdr.agentCredentials.enable`) is declared in
# config/home/herdr.nix, not here, because Home Manager user modules receive the
# Home Manager submodule's OWN config: `config.agentOps` — a NixOS option —
# does not exist inside herdr.nix, while `config.home` and `config.xdg` do.
# Declaring it system-side and reading it from a user module silently yields
# "attribute 'agentOps' missing". So the switch lives with the unit it switches,
# and this module owns the policy and the operator-facing documentation.
#
# ── The delivery paths that exist ────────────────────────────────────────────
# There are exactly three, and nothing else is allowed:
#
#   1. ON DEMAND, VALUES-AS-DATA. `secret-env.sh --exec CMD` (or the fish
#      `ns-secrets run CMD`) reads the decrypted files as bytes and hands them to
#      execve. Scoped to the one process that asked. This is the DEFAULT and it
#      is what the agents use.
#   2. SYSTEMD CREDENTIALS. `LoadCredential=NAME:path` copies the decrypted file
#      into a private, per-service $CREDENTIALS_DIRECTORY. Only that service and
#      its children can read it. Used for restic's repository and password and,
#      optionally, for the herdr server's own spawns.
#   3. EXPLICIT SESSION SCOPE. `ns-secrets` with no arguments sets the values as
#      fish variables in the current interactive shell only. Not persistent, not
#      exported to child processes' children unless asked again.
#
# What no longer exists, and why it is worth a module to say so:
#
#   * a sops TEMPLATE containing `export NAME="value"`, sourced by ~/.profile,
#     by fish, and by a systemd unit that ran `systemctl --user
#     import-environment`. That last one put every credential into the
#     environment of every process in the user session — the browser, the
#     dashboard, sys-daemon, all of them — when they were meant for agents. It
#     was also a source/eval template: a value containing `"` ended the quoting
#     and the remainder was parsed as shell, and a value containing `$(…)` or a
#     backtick was EXECUTED.
#   * `home.sessionVariables` entries of the form `"$(cat /run/secrets/X)"`,
#     which re-parse a value as shell text on every login, cannot represent a
#     multiline value at all, and do not run when there is no login — which, with
#     `linger`, is the normal state of this machine.
#
# ── Anthropic OAuth precedence ──────────────────────────────────────────────
# ANTHROPIC_API_KEY is marked `sessionVariable = false` in env-secrets.nix and
# stays that way. When a Claude Agent SDK client finds ANTHROPIC_API_KEY in its
# environment it bills a $0-credit console account INSTEAD of using the Pro OAuth
# token, which is silent: the requests succeed, the console balance does not
# move. So it is excluded from every delivery path that would put it in an
# ambient environment, and `secret-env.sh --exec` will hand it over only when
# asked for by name. The exclusion is asserted in the test suite, not just
# commented.
{lib, ...}: {
  config = {
    # Documented where an operator will look rather than in a code comment, and
    # readable without root.
    environment.etc."agent-ops/credential-paths.txt".text = ''
      # How credentials reach processes on this host.
      # Generated by nixos/config/system/agent-ops/credentials.nix.

      1. ON DEMAND (the default)
           ns-secrets run <cmd>      # one process, values as data, via execve
           ns-secrets check          # readiness; names and booleans only

      2. SYSTEMD CREDENTIALS
         \$CREDENTIALS_DIRECTORY/<name>, readable only by the service that was
         given the credential. Used by restic (repository + password) and,
         when agentOps.credentials.deliverToHerdr is set, by herdr.service.

      3. EXPLICIT SESSION SCOPE
           ns-secrets                 # current interactive shell only

      NOT AVAILABLE, on purpose:
         * a sourced `export NAME="value"` template of any kind;
         * `systemctl --user import-environment` of decrypted credentials;
         * ANTHROPIC_API_KEY in any ambient environment — the Claude Agent SDK
           prefers it over an OAuth token and bills a different account.

      Readiness: ~/.config/agent-ops/secret-env --check
      Names:      ~/.config/agent-ops/secrets.manifest   (names only, no values)
    '';
  };
}
