# nixos/config/system/agent-ops/credentials.nix
#
# User CLI credentials are loaded into Home Manager's session variables and
# imported into the user manager from the SOPS-generated secrets-env template.
# They are inherited by shells, Herdr panes and their child processes.
#
# Service-only credentials continue to use systemd LoadCredential. The
# secret-env helper remains available to system services that need to read SOPS
# values as data without placing them in command lines or logs.
#
# ── Anthropic OAuth precedence ──────────────────────────────────────────────
# ANTHROPIC_API_KEY is marked `sessionVariable = false` in env-secrets.nix and
# stays that way. When a Claude Agent SDK client finds ANTHROPIC_API_KEY in its
# environment it bills a $0-credit console account INSTEAD of using the Pro OAuth
# token, which is silent: the requests succeed, the console balance does not
# move. So it remains excluded from the session environment; the exclusion is
# set by sessionVariable=false in env-secrets.nix.
{lib, ...}: {
  config = {
    # Documented where an operator will look rather than in a code comment, and
    # readable without root.
    environment.etc."agent-ops/credential-paths.txt".text = ''
      # How credentials reach processes on this host.
      # Generated by nixos/config/system/agent-ops/credentials.nix.

      1. USER SESSION CREDENTIALS
         Home Manager session variables backed by the SOPS secrets-env template.
         Imported into the user manager and inherited by shells, Herdr panes,
         and their child processes.

      2. SYSTEMD CREDENTIALS
         \$CREDENTIALS_DIRECTORY/<name>, readable only by the service that was
         given the credential. Used by restic (repository + password) and other
         service-only credentials.

      3. SYSTEM CHECKS
         ~/.config/agent-ops/secret-env --check
         The values-as-data helper is used by system checks and services.

      ANTHROPIC_API_KEY is excluded from the session environment because the
      Claude Agent SDK prefers it over an OAuth token and bills a different
      account.

      Readiness: ~/.config/agent-ops/secret-env --check
      Names:      ~/.config/agent-ops/secrets.manifest   (names only, no values)
    '';
  };
}
