# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  opts,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/293eef54-23c9-4589-bca2-8506552dd471";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/60B3-03EA";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # --- Shared NTFS Drive for Windows and NixOS ---
  #
  # Mounted when opts.mountShared is true (nixos/options.nix), which it now is.
  # It was OFF here for one reason, and that reason is satisfied rather than
  # ignored: Fast Startup is disabled in Windows, so a Windows shutdown leaves
  # this volume cleanly unmounted instead of hibernated. ntfs3 `rw` on a
  # hibernated volume is a way to corrupt it, and the repair needs a booted
  # Windows and a keyboard — neither of which an unattended box has.
  #
  # 🔴 Fast Startup is Windows-side state this repository cannot enforce. If it
  # is re-enabled, this `rw` mount is a corruption risk again; verify with
  # `powercfg /a` and `powercfg /h`. See opts.mountShared for the full note.
  #
  # Two things worth remembering now that this carries real data:
  #   * `nofail` means a failed mount is silent. Check `findmnt /mnt/shared`
  #     rather than assuming the path is populated.
  #   * Nothing server-critical is here. Every state and media root is a native
  #     Linux filesystem, so a missing mount costs convenience, not the box.
  #
  # Deliberately NOT changed: the partition is not repartitioned, not
  # reformatted, not resized and not given a different UUID, and the kernel
  # still has ntfs3 available (boot.supportedFilesystems) so a file can be
  # copied off it by hand during recovery.
  fileSystems."/mnt/shared" = lib.mkIf opts.mountShared {
    device = "/dev/disk/by-uuid/D8ECDAADECDA8562";
    fsType = "ntfs3";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
      "nofail"
      "exec"
      "fmask=0000" # Grants +x permissions to all files
      "dmask=0000" # Grants +x permissions to all directories
      "iocharset=utf8"
      "discard"
    ];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/e6e3dbd5-40f6-4654-a011-1c4bb0b259e6";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp118s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
