# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  opts,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/293eef54-23c9-4589-bca2-8506552dd471";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/60B3-03EA";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # --- Shared NTFS Drive for Windows and NixOS ---
  #
  # OFF unless opts.mountShared is true (nixos/options.nix). The reasons are
  # about unattended operation, not about NTFS:
  #
  #   * Windows Fast Startup leaves the volume HIBERNATED. ntfs3 mounted rw on
  #     a hibernated volume is a way to corrupt it, and the repair needs a
  #     booted Windows and a keyboard — neither of which an unattended box has.
  #   * `nofail` was doing the work of "if it does not mount, carry on", which
  #     is right, and then nothing noticed whether it mounted at all. On a
  #     machine reached only over the tailnet, a mount that silently did not
  #     happen is discovered by the thing you needed the files for.
  #   * Nothing server-critical reads or writes this path. Every state and
  #     media root in this configuration is a native Linux filesystem.
  #
  # Deliberately NOT changed: the partition is not repartitioned, not
  # reformatted, not resized and not given a different UUID, and the kernel
  # still has ntfs3 available (boot.supportedFilesystems) so a file can be
  # copied off it by hand during recovery without it being mounted at boot.
  # Flipping this on is one boolean.
  fileSystems."/mnt/shared" = lib.mkIf opts.mountShared {
    device = "/dev/disk/by-uuid/D8ECDAADECDA8562";
    fsType = "ntfs3";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
      "nofail"
      "exec"
      "fmask=0000" # Grants +x permissions to all files
      "dmask=0000" # Grants +x permissions to all directories
      "iocharset=utf8"
      "discard"
    ];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/e6e3dbd5-40f6-4654-a011-1c4bb0b259e6";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp118s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
