# shellcheck shell=bash
# This file is a FRAGMENT: config/home/travel.nix reads it with
# builtins.readFile and passes it to writeShellApplication, which adds the
# shebang. So there is deliberately no `#!/` here — and without the
# `shell` directive above, shellcheck refuses to lint it at all (SC2148)
# because it has no way to tell what shell the text is meant for.
# Generated by nixos/config/home/travel.nix.
set -euo pipefail

# ── Refuse rather than repair ──────────────────────────────────────
#
# 🔴 NOTHING HERE EVER RESTARTS, UPGRADES OR REPLACES A herdr SERVER.
#
# The server is the thing your agents are running inside. A helper that
# "fixes" a version mismatch by restarting it kills every open session,
# and one that "updates" it replaces a binary out from under work in
# progress. Both are irreversible from here, and neither is a
# travel-workflow concern. The correct response to an incompatible
# server is to say so and use the local fallback.
check_capabilities() {
  local status client_gen server_gen
  status="$(herdr status 2>&1)" || {
    printf 'herdr-travel: cannot reach a local herdr server.\n' >&2
    printf '  Run locally instead: herdr-travel local <cmd>\n' >&2
    printf '  (the fallback needs no server, which is the point of it.)\n' >&2
    return 1
  }
  client_gen="$(printf '%s\n' "$status" | sed -n 's/.*endpoint_protocol_generation: *//p' | head -1)"
  server_gen="$(printf '%s\n' "$status" | sed -n 's/.*private_protocol: *//p' | head -1)"

  if [[ -z "$client_gen" || -z "$server_gen" ]]; then
    printf 'herdr-travel: could not determine protocol generations from herdr status.\n' >&2
    printf '               Refusing to guess. Use the local fallback (--local).\n' >&2
    return 1
  fi

  if ((client_gen < server_gen)); then
    printf 'herdr-travel: REFUSING — incompatible herdr.\n' >&2
    printf '  client speaks protocol generation %s, server requires %s.\n' \
      "$client_gen" "$server_gen" >&2
    printf '  This is fixed by updating the herdr CLI on THIS machine\n' >&2
    printf '  (herdr update), or by using a client that already matches.\n' >&2
    printf '  The server is NOT restarted or replaced automatically:\n' >&2
    printf '  it holds your running agents.\n' >&2
    return 1
  fi
  printf '%s' "$status"
}

resolve_machine() {
  # An id, not a label. `herdr --remote` takes an SSH target; commands
  # against an already-attached machine take --machine <id>, and a
  # LABEL is resolved by the client. Asking the server is what keeps
  # this working across a machine being re-created.
  local label="$1" id
  id="$(herdr machine list --json 2>/dev/null |
    python3 -c '
import json,sys
label=sys.argv[1]
try:
    data=json.load(sys.stdin)
except Exception:
    sys.exit(1)
machines = data if isinstance(data,list) else data.get("machines",[])
for m in machines:
    if m.get("label")==label or m.get("name")==label:
        print(m.get("id") or m.get("remoteId") or "")
        sys.exit(0)
sys.exit(1)
      ' "$label")" || {
    printf 'herdr-travel: no saved machine labelled %s.\n' "$label" >&2
    printf '  List them: herdr machine list\n' >&2
    printf '  Add one:  herdr --remote %s\n' "$label" >&2
    return 1
  }
  [[ -n "$id" ]] || { printf 'herdr-travel: machine %s has no id.\n' "$label" >&2; return 1; }
  printf '%s' "$id"
}

cmd_status() { herdr status; herdr machine list; }

cmd_attach() {
  check_capabilities >/dev/null
  local id; id="$(resolve_machine "$1")" || return 1
  # Explicit machine on EVERY call. There is no implicit remote context.
  herdr --machine "$id" session attach "${2:-main}"
}

cmd_run() {
  check_capabilities >/dev/null
  local id; id="$(resolve_machine "$1")" || return 1
  shift
  herdr --machine "$id" "$@"
}

# The offline fallback. Runs here, on the laptop, with no dependency on
# the server being reachable at all — which is the point: a hotel wifi
# that cannot reach the basement must not also mean no work.
cmd_local() { exec "$@"; }

usage() {
  cat >&2 <<'USAGE'
usage: herdr-travel <command>

  status                    local server + saved machines
  attach  <label> [session] attach to a saved remote machine
  run     <label> <cmd...>  run a command against a saved remote machine
  local   <cmd...>          run locally; ignores the server entirely

Every remote command passes an explicit --machine <id>. Selecting a
machine in the UI does not retarget your shell, so nothing here depends
on an implicit remote context.

Nothing here restarts, upgrades or replaces a herdr server.
USAGE
}

case "${1:-}" in
  status) shift; cmd_status "$@" ;;
  attach) shift; cmd_attach "$@" ;;
  run) shift; cmd_run "$@" ;;
  local) shift; [[ $# -gt 0 ]] || { usage; exit 2; }; cmd_local "$@" ;;
  *) usage; exit 2 ;;
esac