# nixos/config/home/sops.nix
{
  config,
  inputs,
  lib,
  pkgs,
  ...
}: let
  protonServers = import ./vpn/proton-servers.nix;
  envSecrets = import ./env-secrets.nix;
  sessionVariableNames = lib.concatMap (
    s:
      if s.sessionVariable or true
      then [s.name] ++ (s.aliases or [])
      else []
  ) envSecrets;

  mkVpnTemplate = server: {
    name = "vpn-${server.name}.conf";
    value = {
      path = "${config.home.homeDirectory}/.vpn/configs/${server.name}.conf";
      mode = "0600";
      content = ''
        # ${server.label}
        [Interface]
        PrivateKey = ${config.sops.placeholder.PROTON_VPN_PRIVATE_KEY}
        Address = 10.2.0.2/32, 2a07:b944::2:2/128
        DNS = 10.2.0.1, 2a07:b944::2:1

        [Peer]
        PublicKey = ${server.pubkey}
        AllowedIPs = 0.0.0.0/0, ::/0
        Endpoint = ${server.endpoint}
        PersistentKeepalive = 25
      '';
    };
  };

  # A credential is described to the loader by name only. Nothing here is a
  # value, so the manifest is safe to commit, print, diff and read in a log.
  #
  # `|`-separated, because the loader validates it and a tab-separated format
  # with an empty middle field silently shifts every later field left (tab is
  # IFS whitespace). See config/home/scripts/scripts/secret-env.sh.
  credentialManifest =
    lib.concatStringsSep "\n" (
      map (
        s: "${s.name}|${builtins.concatStringsSep " " (s.aliases or [])}|${
          if s.sessionVariable or true
          then "true"
          else "false"
        }"
      )
      envSecrets
    )
    + "\n";
in {
  imports = [
    inputs.sops-nix.homeManagerModules.sops
  ];

  sops = {
    age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";
    defaultSopsFile = ../../secrets.yaml;

    # Declare all secrets used in templates.
    # Simple string secrets come from env-secrets.nix (see add_env_secret);
    # file-based / one-off secrets are declared here directly.
    secrets =
      (builtins.listToAttrs (map (s: {
          name = s.name;
          value = {};
        })
        envSecrets))
      // {
        # Proton VPN WireGuard private key
        PROTON_VPN_PRIVATE_KEY = {};

        # File-based secrets
        "github_ssh_key" = {
          path = "${config.home.homeDirectory}/.ssh/github_snorreks";
          mode = "0600";
        };
        "aws_credentials" = {
          path = "${config.home.homeDirectory}/.aws/credentials";
          mode = "0600";
        };

        # base64 tar.gz of Thunderbird account/auth files (prefs.js, logins,
        # OpenPGP keys, address book) — NOT the mail store. See
        # backup_thunderbird_profile / restore_thunderbird_profile.
        "thunderbird_profile_bundle" = {
          path = "${config.home.homeDirectory}/.config/sops/thunderbird-profile-bundle.b64";
          mode = "0600";
        };
        # 🔴 Backup-repository and heartbeat credentials are NOT declared here.
        #
        # Declaring a sops secret that does not exist in secrets.yaml fails the
        # build for every host, and inventing one is worse. They are declared by
        # config/system/agent-ops/backup.nix and health.nix, behind their own
        # `enable` flags, so a generation only demands a credential once the
        # feature that uses it has actually been turned on — and turning it on
        # without adding the secret fails loudly instead of silently.
      };

    templates = {
      # Make SOPS credentials available to login shells and the user manager.
      # Only session credentials are exported. Read their files as data, never
      # substitute plaintext into shell syntax. The sentinel preserves trailing
      # newlines that command substitution would otherwise strip.
      "secrets-env" = {
        path = "${config.home.homeDirectory}/.config/sops/secrets-env";
        content =
          lib.concatMapStrings (
            s:
              if s.sessionVariable or true
              then
                lib.concatMapStrings (
                  varName: ''
                    if ${varName}="$(${pkgs.coreutils}/bin/cat -- ${lib.escapeShellArg config.sops.secrets.${s.name}.path} && printf '.')"; then
                      export ${varName}="''${${varName}%.}"
                    fi
                  ''
                ) ([s.name] ++ (s.aliases or []))
              else ""
          )
          envSecrets;
      };

      "nix-access-tokens".content = ''
        access-tokens = github.com=${config.sops.placeholder.GITHUB_ACCESS_TOKEN}
      '';
    };
  };

  nix.extraOptions = ''
    !include ${config.sops.templates."nix-access-tokens".path}
  '';

  xdg.configFile."agent-ops/secrets.manifest" = {
    text = lib.concatStringsSep "\n" [
      "# Generated by nixos/config/home/sops.nix from env-secrets.nix. Do not edit."
      "#"
      "# Names only — never values. Format: NAME|ALIASES(space separated)|SESSION"
      "# where SESSION is true/false and false means the credential must not be"
      "# placed in a session environment. Read by scripts/scripts/secret-env.sh."
      credentialManifest
    ];
    # Deliberately world-readable: the manifest holds NAMES, never values, and
    # the tools that report credential readiness have to be able to read it.
  };

  # The values-as-data loader. home.file rather than xdg.configFile because these
  # must be EXECUTABLE, and `executable` is a home.file option — putting `mode`
  # on an xdg.configFile entry is not an error the module system catches, it just
  # fails with "option does not exist", which is where this started.
  home.file.".config/agent-ops/secret-env" = {
    source = ./scripts/scripts/secret-env.sh;
    executable = true;
  };

  home.file.".config/agent-ops/herdr-daemon-check" = {
    source = ./scripts/scripts/herdr-daemon-check.sh;
    executable = true;
  };

  home.file.".config/agent-ops/herdr-resume" = {
    source = ./scripts/scripts/herdr-resume.sh;
    executable = true;
  };

  systemd.user.services.sops-import-environment = {
    Unit = {
      Description = "Import SOPS decrypted secrets into systemd user environment";
      After = ["sops-nix.service"];
      PartOf = ["sops-nix.service"];
    };
    Install.WantedBy = ["default.target"];
    Service = {
      Type = "oneshot";
      RemainAfterExit = true;
      # Import by name: systemctl's whole-environment import skips values with
      # control characters, including newlines.
      ExecStart = "${pkgs.bash}/bin/bash -c 'if [ -f ~/.config/sops/secrets-env ]; then source ~/.config/sops/secrets-env; ${pkgs.systemd}/bin/systemctl --user import-environment ${lib.concatStringsSep " " sessionVariableNames}; fi'";
    };
  };

  home.file.".profile".text = ''
    if [ -f "$HOME/.config/sops/secrets-env" ]; then
      . "$HOME/.config/sops/secrets-env"
    fi
  '';
}
