# nixos/config/home/travel.nix
#
# The travel laptop's half of the media/travel workflow: named, host-key-pinned
# SSH aliases for the basement server, and native herdr remote attachment.
#
# ── Why this is a new file rather than an addition to herdr.nix ─────────────
# config/home/herdr.nix is owned by the agent-operations lane and is where the
# herdr SERVICE lives — its unit, its daemon-root pinning, its restart
# behaviour. None of that is what this file is about. What this file does is
# CLIENT-side: how to reach the server, and how to run a command against a
# remote machine without retargeting the local one by accident. Adding that to
# herdr.nix would put two unrelated concerns in one file and make the next lane
# edit this one.
#
# ── The thing that actually bites: --machine is not sticky ───────────────
# 🔴 SELECTING A MACHINE IN THE UI DOES NOT RETARGET YOUR SHELL.
#
# `herdr` is a CLI that talks to a local socket. Typing a bare command runs it
# against the LOCAL server no matter what is selected, attached or visible on
# screen. So "I clicked the Legion and ran a command" is not a thing that
# happens, and a helper that pretends otherwise will quietly run a build on the
# laptop you are holding.
#
# Every remote command here therefore passes an EXPLICIT `--machine <id>`, and
# obtains the id from `herdr machine list` rather than from a hard-coded string
# that a re-created machine invalidates.
{config, lib, opts, pkgs, ...}: let
  cfg = opts.travel;

  # The pin. Empty means "not pinned yet", which is reported as such rather than
  # silently falling back to OpenSSH's TOFU — a first connection prompt on a
  # tailnet is exactly where you do not want a MITM prompt.
  pinned = cfg.serverHostKey != "";

  hostKeyLine = ''
    HostKey ${cfg.serverHostKeyType} ${cfg.serverHostKey}
    StrictHostKeyChecking yes
    UserKnownHostsFile /etc/ssh/ssh_known_hosts.d/travel
    UpdateHostKeys no
  '';
in {
  # ── SSH aliases ────────────────────────────────────────────────────────────
  #
  # TWO aliases because they are two different services, and conflating them is
  # the source of the builder bug this lane fixes:
  #
  #   legion          ordinary OpenSSH on 2222. Key authentication. Use this for
  #                   scripts, the Nix builder, port forwards, automation.
  #   legion-tailscale
  #                   Tailscale SSH on 22. Authenticated by a TAILSCALE IDENTITY,
  #                   not by a key file, which is why it works from a device with
  #                   no private key — and why it cannot be used for anything
  #                   that needs key authentication, including Nix.
  programs.ssh = lib.mkIf cfg.enable {
    extraConfig = ''
      # Generated by nixos/config/home/travel.nix

      Host ${cfg.serverHost}
          HostName ${cfg.serverHost}
          User ${opts.username}
          Port ${toString cfg.sshPort}
          # Tailscale's resolver is deliberately not accepted on this machine
          # (config/system/networking.nix), so the name comes from /etc/hosts —
          # see opts.tailnetHosts.
          IdentityFile ~/.ssh/nixbuilder
          IdentitiesOnly yes
          ServerAliveInterval 30
          ServerAliveCountMax 3
          # Tailscale is a WireGuard mesh: a link that goes quiet rather than
          # closing should be noticed quickly, because the fallback (a plain
          # SSH over the home LAN) is a different trust path entirely.
      ${if pinned then hostKeyLine else ''
          # 🔴 NOT PINNED. opts.travel.serverHostKey is empty.
          #
          # Generated here as a visible, failing configuration rather than a
          # working one: the alternative is a first-connection TOFU prompt,
          # which on a tailnet is exactly where you do not want to be asked to
          # approve a key you did not verify. Populate it and rebuild.
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          LogLevel ERROR
      ''}

      Host ${cfg.serverHost}-tailscale
          HostName ${cfg.serverHost}
          User ${opts.username}
          Port ${toString cfg.tailscalePort}
          # No IdentityFile: this authenticates with a Tailscale identity, so
          # offering a key file here does nothing but wait for the handshake to
          # time out.
          # NOT the builder path — see the header.
    '';
  };

  # ── Native herdr remote attachment ────────────────────────────────────────
  home.packages = lib.mkIf (cfg.enable && cfg.herdrRemote.enable) [
    (pkgs.writeShellApplication {
      name = "herdr-travel";
      runtimeInputs = [pkgs.coreutils pkgs.gnugrep pkgs.which pkgs.ripgrep];
      # The script lives in its own file rather than inline in this module.
      # It is bash full of ${...} and $(), and keeping it here means every
      # shell expansion is also a Nix interpolation that has to be escaped — a
      # class of bug that reads as a Nix syntax error pointing at a shell line.
      text = builtins.readFile ./scripts/herdr-travel.sh;
    })
  ];

  # ── Visible half-configuration ────────────────────────────────────────────
  warnings = lib.mkIf (cfg.enable && cfg.herdrRemote.enable && !pinned) ''
    travel: opts.travel.serverHostKey is empty, so the SSH aliases are generated
    WITHOUT a host key pin (StrictHostKeyChecking no, UserKnownHostsFile
    /dev/null).

    That is a visible, failing configuration on purpose rather than a working one
    with a first-connection prompt. On a tailnet, an unverified host key prompt
    is exactly the wrong place to be asked to approve a key.

    On the server:
      cat /etc/ssh/ssh_host_ed25519_key.pub
    Then paste the public half into opts.travel.serverHostKey and rebuild.
  '';
}