# nixos/config/home/travel.nix
#
# The travel laptop's half of the media/travel workflow: named, host-key-pinned
# SSH aliases for the basement server, and native herdr remote attachment.
#
# ── Why this is a new file rather than an addition to herdr.nix ─────────────
# config/home/herdr.nix is owned by the agent-operations lane and is where the
# herdr SERVICE lives — its unit, its daemon-root pinning, its restart
# behaviour. None of that is what this file is about. What this file does is
# CLIENT-side: how to reach the server, and how to run a command against a
# remote machine without retargeting the local one by accident. Adding that to
# herdr.nix would put two unrelated concerns in one file and make the next lane
# edit this one.
#
# ── The thing that actually bites: --machine is not sticky ───────────────
# 🔴 SELECTING A MACHINE IN THE UI DOES NOT RETARGET YOUR SHELL.
#
# `herdr` is a CLI that talks to a local socket. Typing a bare command runs it
# against the LOCAL server no matter what is selected, attached or visible on
# screen. So "I clicked the Legion and ran a command" is not a thing that
# happens, and a helper that pretends otherwise will quietly run a build on the
# laptop you are holding.
#
# Every remote command here therefore passes an EXPLICIT `--machine <id>`, and
# obtains the id from `herdr machine list` rather than from a hard-coded string
# that a re-created machine invalidates.
{config, lib, opts, pkgs, ...}: let
  cfg = opts.travel;

  # The pin. Empty means "not pinned yet", which is reported as such rather than
  # silently falling back to OpenSSH's TOFU — a first connection prompt on a
  # tailnet is exactly where you do not want a MITM prompt.
  pinned = cfg.serverHostKey != "";

  # `HostKey` is an sshd_config DIRECTIVE. There is no such option in
  # ssh_config, so the pinned branch made ssh reject the whole file with
  # "Bad configuration option" — the alias did not work at all once pinned.
  #
  # The client-side equivalent is a known_hosts ENTRY, so that is what is
  # written (see `home.file` below) and what `UserKnownHostsFile` points at.
  hostKeyLine = ''
    StrictHostKeyChecking yes
    UserKnownHostsFile ~/.ssh/known_hosts.travel
    UpdateHostKeys no
  '';

  # The pinned entry itself: "<host> <type> <key>", the known_hosts(5) format.
  # Written only when a key has been configured, so the file never exists in an
  # unpinned machine's half-finished state.
  knownHostsEntry = "${cfg.serverHost} ${cfg.serverHostKeyType} ${cfg.serverHostKey}";
in {
  # ── SSH aliases ────────────────────────────────────────────────────────────
  #
  # TWO aliases because they are two different services, and conflating them is
  # the source of the builder bug this lane fixes:
  #
  #   legion          ordinary OpenSSH on 2222. Key authentication. Use this for
  #                   scripts, the Nix builder, port forwards, automation.
  #   legion-tailscale
  #                   Tailscale SSH on 22. Authenticated by a TAILSCALE IDENTITY,
  #                   not by a key file, which is why it works from a device with
  #                   no private key — and why it cannot be used for anything
  #                   that needs key authentication, including Nix.
  programs.ssh = lib.mkIf cfg.enable {
    extraConfig = ''
      # Generated by nixos/config/home/travel.nix

      Host ${cfg.serverHost}
          HostName ${cfg.serverHost}
          User ${opts.username}
          Port ${toString cfg.sshPort}
          # Tailscale's resolver is deliberately not accepted on this machine
          # (config/system/networking.nix), so the name comes from /etc/hosts —
          # see opts.tailnetHosts.
          IdentityFile ~/.ssh/nixbuilder
          IdentitiesOnly yes
          ServerAliveInterval 30
          ServerAliveCountMax 3
          # Tailscale is a WireGuard mesh: a link that goes quiet rather than
          # closing should be noticed quickly, because the fallback (a plain
          # SSH over the home LAN) is a different trust path entirely.
      ${if pinned then hostKeyLine else ''
          # ð NOT PINNED, AND THIS REFUSES TO CONNECT.
          #
          # This was `StrictHostKeyChecking no` with `UserKnownHostsFile
          # /dev/null` and `LogLevel ERROR` — which is WEAKER than trust-on-first-use,
          # not stronger: every key is accepted on every connection with no
          # warning at all, so an impostor on the tailnet path or the LAN
          # fallback is trusted silently, and forwarded sessions go to it.
          #
          # `yes` plus an empty known_hosts file means the connection FAILS until
          # the key is pinned. That is the correct failure: a loud one at the
          # moment you are on the machine, rather than a quiet one later.
          StrictHostKeyChecking yes
          UserKnownHostsFile /dev/null
          LogLevel VERBOSE
      ''}

      Host ${cfg.serverHost}-tailscale
          HostName ${cfg.serverHost}
          User ${opts.username}
          Port ${toString cfg.tailscalePort}
          # No IdentityFile: this authenticates with a Tailscale identity, so
          # offering a key file here does nothing but wait for the handshake to
          # time out.
          # NOT the builder path — see the header.
    '';
  };

  # ── The pinned key, as a known_hosts entry ────────────────────────────────
  #
  # This is what makes the pin real. Without a file containing the entry, and
  # with `StrictHostKeyChecking yes`, ssh would fail on every connection — which
  # is the safe failure, but it means the pinned state never actually works.
  #
  # A SEPARATE file rather than ~/.ssh/known_hosts: that one grows live as ssh
  # appends newly-trusted hosts, and nixos/tests' own history records home
  # manager fighting that file over backups.
  home.file = lib.mkIf (cfg.enable && pinned) {
    ".ssh/known_hosts.travel".text = knownHostsEntry + "\n";
  };

  # ── Native herdr remote attachment ────────────────────────────────────────
  home.packages = lib.mkIf (cfg.enable && cfg.herdrRemote.enable) [
    (pkgs.writeShellApplication {
      name = "herdr-travel";
      # python3 and sed are CALLED by the script. Without them on PATH,
      # resolve_machine fails and reports "no saved machine labelled legion" —
      # a message that hides the real cause completely. `herdr` is deliberately
      # NOT here: it is the user's own installed binary, and pinning one in
      # would put a second version in the store next to it.
      runtimeInputs = [
        pkgs.coreutils
        pkgs.gnugrep
        pkgs.python3
      ];
      # The script lives in its own file rather than inline in this module.
      # It is bash full of ${...} and $(), and keeping it here means every
      # shell expansion is also a Nix interpolation that has to be escaped — a
      # class of bug that reads as a Nix syntax error pointing at a shell line.
      text = builtins.readFile ./scripts/herdr-travel.sh;
    })
  ];

  # ── Visible half-configuration ────────────────────────────────────────────
  # `lib.optional`, not `lib.mkIf`: `warnings` is a listOf str, and mkIf wraps
  # the STRING rather than the list, so the moment the condition became true
  # evaluation failed instead of warning.
  #
  # The condition does NOT include herdrRemote.enable: the pin is about the SSH
  # ALIASES, which exist whenever travel is enabled. Gating on herdrRemote
  # (default false) meant the GS65 never saw the warning about its own unpinned
  # aliases.
  warnings = lib.optional (cfg.enable && !pinned) ''
    travel: opts.travel.serverHostKey is empty, so the SSH aliases are generated
    WITHOUT a host key pin: StrictHostKeyChecking yes with an empty
    known_hosts file, so every connection to it FAILS.

    That is deliberate, and it is the opposite of the earlier behaviour, which
    was `StrictHostKeyChecking no` plus `UserKnownHostsFile /dev/null` plus
    LogLevel ERROR — weaker than trust-on-first-use, because every key was
    accepted on every connection with no warning printed at all.

    A loud failure while you are sitting at the machine beats a quiet one on a
    hotel network.

    On the server:
      cat /etc/ssh/ssh_host_ed25519_key.pub
    Then paste the public half into opts.travel.serverHostKey and rebuild.
  '';
}