#!/usr/bin/env bash
# legion-term — a foot terminal whose shell RUNS ON THE LEGION.
#
# WHAT THIS IS
#   Every prompt, every keystroke and every byte of output belongs to the server.
#   The local side is only a terminal emulator painting a remote PTY. Nothing is
#   executed on this machine except ssh itself and foot's own drawing.
#
# WHY THIS IS NOT JUST `foot ssh legion`
#   Two ways that one-liner fails, both of which look like "foot flashed and
#   died" — the least informative outcome a hotkey can have:
#
#     * The `legion` alias is GENERATED, by config/home/travel.nix, and only on
#       a host with opts.travel.enable. Without it ssh does not error: it falls
#       back to port 22, which on this tailnet is Tailscale SSH, a different
#       service authenticating by identity and demanding an interactive browser
#       check. So a missing alias presents as the wrong machine on the wrong
#       port rather than as a missing alias.
#     * Tailscale logged out, or the Legion unreachable — in which case ssh
#       would print its own diagnosis to a stdout mango has already discarded.
#
#   Hence the pre-flight: the alias is resolved, the identity it names is
#   checked to exist, and the port is probed BEFORE a window opens. On failure
#   the reason is shown IN a terminal, because `spawn` throws stdout away.
#
# `ssh -G` prints the effective configuration and exits 0 even for a host it has
# never heard of (it falls back to port 22 and the default identity list), so it
# cannot be used on its own to prove the alias exists. That is why the check is
# "does a named identity actually exist on disk", which is the thing that
# distinguishes a generated alias from a default fallback.
#
# LATENCY, stated rather than hidden: this is a 150–250 ms round trip, so
# keystrokes visibly lag and full-screen TUIs are unpleasant. Applying patches,
# builds, ollama and long-running jobs are unaffected in practice. If interactive
# typing becomes the thing you do most, mosh is the fix — it needs the `mosh`
# client here and the mosh-server listener on the Legion, and no key exchange
# per reconnect. It is deliberately NOT wired in automatically: a launcher that
# silently changes transport is a launcher whose behaviour you cannot predict
# from its name.
#
# Overridable for testing or for a second server: LEGION_TERM_HOST,
# LEGION_TERM_TITLE, LEGION_TERM_TIMEOUT.
set -uo pipefail

host="${LEGION_TERM_HOST:-legion}"
title="${LEGION_TERM_TITLE:-legion}"
probe_timeout="${LEGION_TERM_TIMEOUT:-4}"

# Everything below is interpolated into a `bash -c` / `sh -c` string and into a
# foot argument, so the host is constrained to what an ssh alias may legally
# look like. A name carrying a space or a quote would otherwise turn a lookup
# failure into code execution.
if [[ ! "$host" =~ ^[A-Za-z0-9._-]+$ ]]; then
  printf 'legion-term: refusing to use host name %q\n' "$host" >&2
  exit 2
fi

# Show the reason in a window rather than on a stdout nobody is reading.
fail() {
  foot --title="$title — not connected" --app-id=legion-term \
    sh -c 'printf "%s\n" "$1"; printf "\nPress Enter to close.\n"; read -r _' sh "$1"
  exit 1
}

command -v ssh >/dev/null 2>&1 || fail "ssh is not on PATH on this machine."

# `ssh -G` exits 0 even for an unknown host, so its output is evidence, not a
# verdict.
ssh_cfg="$(ssh -G "$host" 2>/dev/null)" || fail "ssh could not resolve the host alias '$host'."

port="$(awk '$1 == "port" {print $2; exit}' <<<"$ssh_cfg")"
user="$(awk '$1 == "user" {print $2; exit}' <<<"$ssh_cfg")"
[[ "$port" =~ ^[0-9]+$ ]] || fail "No usable port for '$host'; the ssh config is not generated as expected."

# The generated alias names a specific identity. A fallback to defaults lists a
# whole column of files, none of which may exist — so look for one that does.
identity=""
while read -r candidate; do
  # `ssh -G` prints identityfile paths VERBATIM, so a generated alias yields
  # "~/.ssh/nixbuilder" — with a tilde, which [[ -f ]] does not expand. Testing
  # that string directly reports a perfectly good identity as missing.
  candidate="${candidate/#\~/$HOME}"
  [[ -f "$candidate" ]] && identity="$candidate" && break
done < <(awk '$1 == "identityfile" {print $2}' <<<"$ssh_cfg")

if [[ -z "$identity" ]]; then
  fail "No usable SSH identity for '$host'.
The 'legion' alias is generated by config/home/travel.nix and only exists on a
host with opts.travel.enable. Without it ssh would quietly use port ${port}
instead. Rebuild after a change to that module."
fi

# Tailscale first, because "logged out" is the most common cause and it is the
# one case where the name would otherwise resolve to nothing at all.
if ! ts_state="$(tailscale status 2>&1)"; then
  fail "Tailscale is not answering on this machine.
  $ts_state"
fi
if grep -qi "logged out" <<<"$ts_state"; then
  fail "Tailscale is logged out on this machine.
Join the tailnet first:  sudo tailscale login"
fi

if ! timeout "$probe_timeout" bash -c "exec 3<>/dev/tcp/$host/$port" 2>/dev/null; then
  fail "Cannot reach $user@$host on port $port (${probe_timeout}s).
The tailnet is up but the port is closed. If the Legion is rebooting, wait and
retry. Otherwise check that sshd is listening there:
  tailscale ping $host"
fi

# -t forces PTY allocation: without it an interactive program on the far side
# sees a pipe, and the prompt, colours and job control are all wrong.
exec foot --title="$title" --app-id=legion-term ssh -t "$host"