#!/usr/bin/env bash
# secret-env.sh — load SOPS-decrypted credentials as VALUES-AS-DATA.
#
# ── What this replaces, and why ───────────────────────────────────────────────
# There used to be a sops *template*, `~/.config/sops/secrets-env`, containing
#
#     export OPENROUTER_API_KEY="sk-or-v1-…"
#
# sourced by three separate places: `~/.profile`, fish's interactiveShellInit,
# and `sops-import-environment.service` (which did `systemctl --user
# import-environment`, pushing every secret into the environment of EVERY
# process in the user session). That is a source/eval template and it was wrong
# in five ways at once:
#
#   1. A value containing `"` terminated the quoting early and the remainder
#      was parsed as SHELL. A value containing `$(…)`, backticks or `;` was
#      *executed*.
#   2. A multiline value could not survive at all: the template is line
#      oriented, `while read -l line` in fish truncated it to the first line,
#      and the `.profile` fragment was a syntax error.
#   3. `import-environment` put every credential into the environment of every
#      process in the session — the dashboard, the browser, sys-daemon, whatever
#      else — when the credentials were meant for the agents.
#   4. Nothing ran it when there was no login shell. The whole point of
#      `linger` is that there is no login; the herdr server therefore started at
#      boot with no credentials at all and every agent it spawned was blind.
#   5. The fish parser that read it was itself broken: the pattern was
#      `'^export\s+([^=]+)=(.*)\$'`, which requires the line to END with a
#      literal `$`. It matched essentially nothing, and nothing noticed because
#      the desktop path also had `~/.profile`.
#
# This script never parses, evaluates or expands a value. It reads bytes from a
# file and hands them to `execve` as an environment entry. There is no code
# path in which a secret value becomes code.
#
# ── Where values come from ───────────────────────────────────────────────────
# A manifest — generated by Nix from nixos/config/home/env-secrets.nix, so the
# names still have exactly one source of truth — lists which credentials exist.
# Values come from files only, searched in this order:
#
#   1. $CREDENTIALS_DIRECTORY        systemd LoadCredential= (preferred)
#   2. $XDG_RUNTIME_DIR/sops-nix/secrets
#   3. ~/.local/state/sops-nix/secrets
#
# Every one of those is a decrypted-at-rest file owned by the service that was
# given the credential, so scoping is done by systemd, not by hoping.
#
# ── Manifest format ───────────────────────────────────────────────────────────
# Pipe-separated, data only. Fields: NAME | ALIASES (space separated, may be
# empty) | SESSION ("true" or "false"). Blank lines and #-comments ignored.
#
# `|`, not TAB: tab is IFS whitespace in bash, so a TAB-separated format with an
# empty middle field silently shifts every later field left by one — `NAME<TAB><TAB>true`
# parses as ALIASES="true", SESSION="". The credential whose session flag was
# misread is exactly the one that decides whether a secret reaches the session.
# `|` cannot occur in a name ([A-Za-z0-9_]) or in "true"/"false", so the split is
# unambiguous.
#
# Anything that does not match exactly is a hard error naming the line — the
# manifest is generated, so a malformed one is a Nix bug, not user input, and it
# must fail loudly rather than silently drop credentials.
#
# ── Newline and NUL semantics (the part that has to be written down) ─────────
#   * A value is the file's bytes with AT MOST ONE trailing newline removed.
#     That is what a user means when they create a secret file from a text
#     editor or `echo`, and it is the only transformation applied.
#   * EMBEDDED newlines are preserved verbatim and are legal. A PEM private
#     key is three lines; this script round-trips it. (It cannot be put in a
#     *shell* variable on one line, which is why --exec and the fish wrapper
#     both go through the process environment rather than through a string.)
#   * A NUL byte is REJECTED. `execve` cannot represent one in an environment
#     string, and truncating at it would silently hand a caller half a secret.
#     The error names the credential and the offset.
#   * Leading/trailing whitespace other than that single newline is NOT
#     stripped. A secret with trailing spaces is a secret with trailing spaces.
#   * The value is never written to a log, to stdout in --format=list/json, to
#     a process title, or to a file this script owns.
#
# ── Exit codes ────────────────────────────────────────────────────────────────
#   0  ok          2  usage / bad name      3  not ready (a credential is absent)
#   4  malformed value (embedded NUL)       5  --exec target failed
set -o nounset -o pipefail

# errexit is deliberately NOT enabled. This script reports a credential's state
# through its EXIT CODE (0 ready, 3 absent, 4 malformed), and `cmd_or_die`-style
# helpers depend on evaluating a command that is expected to fail. Turning on
# errexit anywhere upstream of that would make "absent" exit the script at the
# first read instead of producing a readiness report.
set +o errexit

PROGRAM_NAME=${0##*/}

DEFAULT_MANIFEST=${SECRET_ENV_MANIFEST:-$HOME/.config/agent-ops/secrets.manifest}

# ── output ──────────────────────────────────────────────────────────────────
FORMAT=nul
MANIFEST=
declare -a ONLY_NAMES=()
declare -a COMMAND=()

# ── reporting ───────────────────────────────────────────────────────────────
sayf() { printf '%s: %s\n' "$PROGRAM_NAME" "$*" >&2; }

usage() {
	cat >&2 <<EOF
usage: $PROGRAM_NAME [--manifest FILE] [--name NAME]... [--format=FORMAT]
                      [--check] [--exec COMMAND...]

  --manifest FILE   credential manifest (default: \$SECRET_ENV_MANIFEST or
                    ~/.config/agent-ops/secrets.manifest)
  --name NAME       restrict to this credential; repeatable
  --format=FORMAT   nul (default) | env | list | check | json
                      nul   NAME=VALUE, NUL separated, on stdout
                      env   the same, but newline separated (for reading, not
                            for execve — use nul or --exec for a real value)
                      list  credential names only, no values
                      check human-readable readiness
                      json  readiness as JSON, no values
  --check           alias for --format=check
  --exec CMD...     exec CMD with NAME=VALUE in its environment
  --                end of options

exit: 0 ok, 2 usage/name, 3 not ready, 4 malformed value, 5 exec failed
EOF
	exit 2
}

die_usage() {
	sayf "$*"
	usage
}

# ── name validation ─────────────────────────────────────────────────────────
#
# A credential name becomes an environment variable NAME, so it is validated
# against the shell-portable grammar rather than trusted. Anything outside
# [A-Za-z_][A-Za-z0-9_]* cannot be exported safely and, worse, could be used
# to smuggle something that looks like an option or a path.
valid_name() { [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; }

require_valid_name() {
	local what="$1" name="$2"
	if ! valid_name "$name"; then
		sayf "invalid $what '$name': must match [A-Za-z_][A-Za-z0-9_]*"
		return 2
	fi
	return 0
}

# ── arguments ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
	case "$1" in
	--manifest)
		[[ $# -ge 2 ]] || die_usage "--manifest needs a value"
		MANIFEST="$2"
		shift 2
		;;
	--manifest=*) MANIFEST="${1#--manifest=}"; shift ;;
	--name)
		[[ $# -ge 2 ]] || die_usage "--name needs a value"
		ONLY_NAMES+=("$2")
		shift 2
		;;
	--name=*) ONLY_NAMES+=("${1#--name=}"); shift ;;
	--format=*) FORMAT="${1#--format=}"; shift ;;
	--format)
		[[ $# -ge 2 ]] || die_usage "--format needs a value"
		FORMAT="$2"
		shift 2
		;;
	--check) FORMAT=check; shift ;;
	--list) FORMAT=list; shift ;;
	--exec)
		shift
		[[ $# -ge 1 ]] || die_usage "--exec needs a command"
		COMMAND=("$@")
		break
		;;
	-h | --help) usage ;;
	--) shift; COMMAND=("$@"); break ;;
	-*) die_usage "unknown option '$1'" ;;
	*) die_usage "unexpected argument '$1'" ;;
	esac
done

case "$FORMAT" in
nul | env | list | check | json) ;;
*) die_usage "unknown --format '$FORMAT' (nul, env, list, check, json)" ;;
esac

[[ -n "$MANIFEST" ]] || MANIFEST="$DEFAULT_MANIFEST"

for n in ${ONLY_NAMES[@]+"${ONLY_NAMES[@]}"}; do require_valid_name "--name" "$n" || exit 2; done

# ── the manifest ────────────────────────────────────────────────────────────
#
# Read into name -> (aliases, session) maps. Values are NOT here: the manifest
# only ever says which credentials exist, so it is safe to commit, to print and
# to diff.
declare -A SECRET_ALIASES=()
declare -A SECRET_SESSION=()
declare -a SECRET_ORDER=()

load_manifest() {
	if [[ ! -r "$MANIFEST" ]]; then
		sayf "manifest $MANIFEST is missing or unreadable."
		sayf "This module owns it; a generation without it has no credential names."
		exit 3
	fi
	local lineno=0 raw name aliases session field_count
	while IFS= read -r raw || [[ -n "$raw" ]]; do
		lineno=$((lineno + 1))
		raw="${raw%$'\r'}"
		[[ -z "$raw" || "$raw" == \#* ]] && continue
		field_count="$(awk -F'|' '{print NF}' <<<"$raw")"
		((field_count == 3)) || {
			sayf "$MANIFEST:$lineno: expected 3 '|'-separated fields, got $field_count."
			exit 2
		}
		IFS='|' read -r name aliases session _ <<<"$raw"
		require_valid_name "credential name" "$name" || exit 2
		[[ "$session" == "true" || "$session" == "false" ]] || {
			sayf "$MANIFEST:$lineno: SESSION must be 'true' or 'false', got '$session'."
			exit 2
		}
		for a in $aliases; do
			require_valid_name "alias" "$a" || exit 2
		done
		SECRET_ALIASES["$name"]="$aliases"
		SECRET_SESSION["$name"]="$session"
		SECRET_ORDER+=("$name")
	done <"$MANIFEST"
	((${#SECRET_ORDER[@]} > 0)) || {
		sayf "$MANIFEST lists no credentials."
		exit 3
	}
}

load_manifest

# ── value lookup ────────────────────────────────────────────────────────────
#
# The search list is the whole point of LoadCredential: a service that was not
# given the credential cannot reach it, and this script will not go looking
# somewhere else.
declare -a SEARCH_DIRS=()
[[ -n "${CREDENTIALS_DIRECTORY:-}" ]] && SEARCH_DIRS+=("$CREDENTIALS_DIRECTORY")
[[ -n "${XDG_RUNTIME_DIR:-}" ]] && SEARCH_DIRS+=("$XDG_RUNTIME_DIR/sops-nix/secrets")
SEARCH_DIRS+=("${XDG_STATE_HOME:-$HOME/.local/state}/sops-nix/secrets")

secret_path() {
	local name="$1" dir
	for dir in "${SEARCH_DIRS[@]}"; do
		if [[ -f "$dir/$name" && -r "$dir/$name" ]]; then
			printf '%s' "$dir/$name"
			return 0
		fi
	done
	return 1
}

# read_value NAME — writes the value to stdout, or returns 1.
#
# Exit 4 means "found but malformed", which is NOT the same as "absent": a
# truncated credential must never be handed to a caller as if it were whole.
read_value() {
	local name="$1" path
	if ! path="$(secret_path "$name")"; then
		return 1
	fi
	# NUL detection WITHOUT $'\x00': bash cannot put a NUL in a string, so
	# `$'\x00'` is the EMPTY string and `grep -q ''` matches every file — the
	# first version of this check rejected every credential on earth. Compare
	# byte counts with and without NULs instead.
	local total stripped
	total="$(wc -c <"$path")"
	stripped="$(LC_ALL=C tr -d '\000' <"$path" | wc -c)"
	if [[ "$stripped" != "$total" ]]; then
		sayf "credential '$name' ($path) contains a NUL byte."
		sayf "An environment variable cannot carry one; refusing to hand back a truncated value."
		return 4
	fi
	# Strip AT MOST ONE trailing newline, leave everything else alone.
	local data
	data="$(cat -- "$path"; printf x)"
	data="${data%x}"
	data="${data%$'\n'}"
	printf '%s' "$data"
}

# ── readiness ───────────────────────────────────────────────────────────────
#
# Reports presence, never values. `json` output is what the health module
# consumes, so this shape is part of the interface: an object keyed by
# credential name with a boolean and, when absent, the reason.
declare -a READY_NAMES=()
declare -a ABSENT_NAMES=()
declare -a MALFORMED_NAMES=()

# collect [name...] — fills READY/ABSENT/MALFORMED. Returns 3 if any is not ready.
collect() {
	local -a wanted=("$@")
	((${#wanted[@]} > 0)) || wanted=("${SECRET_ORDER[@]}")

	local n rc path
	for n in "${wanted[@]}"; do
		read_value "$n" >/dev/null 2>&1
		rc=$?
		case "$rc" in
		0) READY_NAMES+=("$n") ;;
		1) ABSENT_NAMES+=("$n") ;;
		4) MALFORMED_NAMES+=("$n") ;;
		*) ABSENT_NAMES+=("$n") ;;
		esac
	done
	((${#MALFORMED_NAMES[@]} == 0)) || return 3
	((${#ABSENT_NAMES[@]} == 0)) || return 3
	return 0
}

session_names() {
	local n
	for n in "${SECRET_ORDER[@]}"; do
		[[ "${SECRET_SESSION[$n]}" == "true" ]] && printf '%s\n' "$n"
	done
	return 0
}

# var_names NAME — every environment variable name this credential answers to:
# its own, plus each alias. Aliases exist because tools disagree (GH_TOKEN vs
# GITHUB_ACCESS_TOKEN), and exporting only one half of that pair is how you get
# a tool that silently authenticates as nobody.
var_names() {
	local n="$1" a
	printf '%s\n' "$n"
	for a in ${SECRET_ALIASES[$n]}; do
		printf '%s\n' "$a"
	done
}

# ── output modes ────────────────────────────────────────────────────────────
emit_check() {
	local rc=0 n
	printf 'credential readiness (%s)\n' "$MANIFEST"
	if ((${#READY_NAMES[@]} > 0)); then
		printf '  ready    %s\n' "${READY_NAMES[*]}"
	fi
	if ((${#ABSENT_NAMES[@]} > 0)); then
		rc=3
		printf '  ABSENT   %s\n' "${ABSENT_NAMES[*]}"
		printf '           no decrypted file in: %s\n' "${SEARCH_DIRS[*]}"
		printf '           sops-nix has not run yet, or this unit was not given\n'
		printf '           the credential. An absent credential is NOT an empty one.\n'
	fi
	if ((${#MALFORMED_NAMES[@]} > 0)); then
		rc=3
		printf '  MALFORMED %s\n' "${MALFORMED_NAMES[*]}"
		printf '            contains a NUL byte; refusing to truncate it.\n'
	fi
	return "$rc"
}

emit_json() {
	local rc=0 first=1 n a path
	printf '{"manifest":%s,"searchDirs":[' "$(json_string "$MANIFEST")"
	for path in "${SEARCH_DIRS[@]}"; do
		((first)) || printf ','
		first=0
		printf '%s' "$(json_string "$path")"
	done
	printf '],"credentials":{'
	first=1
	for n in "${SECRET_ORDER[@]}"; do
		((first)) || printf ','
		first=0
		if read_value "$n" >/dev/null 2>&1; then
			printf '%s:{"ready":true,"session":%s,"aliases":[' \
				"$(json_string "$n")" "${SECRET_SESSION[$n]}"
		else
			rc=3
			printf '%s:{"ready":false,"session":%s,"aliases":[' \
				"$(json_string "$n")" "${SECRET_SESSION[$n]}"
		fi
		local firsta=1
		for a in ${SECRET_ALIASES[$n]}; do
			((firsta)) || printf ','
			firsta=0
			printf '%s' "$(json_string "$a")"
		done
		printf ']}'
	done
	printf '},"ready":%s}\n' "$([[ $rc -eq 0 ]] && echo true || echo false)"
	return "$rc"
}

# Minimal JSON string escaping. The manifest is generated from Nix attribute
# names that are already restricted to [A-Za-z0-9_], so this only has to be
# correct, not clever.
json_string() {
	local s="$1"
	printf '"%s"' "${s//\\/\\\\}"
}

# wanted_names — the credential names this invocation is about: the explicit
# --name list if there is one, otherwise every credential marked session=true.
wanted_names() {
	if ((${#ONLY_NAMES[@]} > 0)); then
		printf '%s\n' "${ONLY_NAMES[@]}"
		return 0
	fi
	session_names
}

emit_nul() {
	local n v a
	while IFS= read -r n; do
		v="$(read_value "$n")" || return $?
		while IFS= read -r a; do
			printf '%s=%s\0' "$a" "$v"
		done < <(var_names "$n")
	done < <(wanted_names)
	return 0
}

emit_lines() {
	wanted_names
	return 0
}

# ── --exec ──────────────────────────────────────────────────────────────────
#
# The only mode that puts a value into a real process environment, and it does
# so with execve: the bytes are never concatenated into a command line, never
# parsed, and never visible in ps output.
# all_credential_names — every credential name and alias in the manifest.
#
# Used to REMOVE credentials that were not requested from the environment we are
# about to hand on, so that an ambient `OPENAI_API_KEY` left over from a parent
# process is not silently inherited by a command that only asked for one
# credential. Names only, never values.
all_credential_names() {
	local n a
	for n in "${SECRET_ORDER[@]}"; do
		var_names "$n"
	done
}

do_exec() {
	local -a pairs=()
	local n rc v a
	for n in "$@"; do
		v="$(read_value "$n")"
		rc=$?
		case "$rc" in
		0) ;;
		1)
			sayf "credential '$n' is absent — refusing to exec."
			return 3
			;;
		4) return 4 ;;
		*) return 3 ;;
		esac
		while IFS= read -r a; do
			pairs+=("$a=$v")
		done < <(var_names "$n")
	done
	((${#pairs[@]} > 0)) || {
		sayf "nothing to exec with: no credential requested."
		return 2
	}
	((${#COMMAND[@]} > 0)) || {
		sayf "--exec needs a command."
		return 2
	}

	# 🔴 SET THE ENVIRONMENT DIRECTLY, NEVER `env -i KEY=VALUE`.
	#
	# `env -i "$@" ...` puts every secret in the ARGUMENT LIST of the `env`
	# process, where any other local user can read it from
	# /proc/<pid>/cmdline or `ps` unless /proc is mounted with hidepid. The
	# header's claim that values are "never visible in ps output" was false for
	# exactly this line.
	#
	# The caller's environment is also PRESERVED, deliberately: `env -i` also
	# cleared TERM, LANG, USER, SSH_AUTH_SOCK and XDG_RUNTIME_DIR, so
	# `ns-secrets run pi` started a terminal program with no terminal and git
	# over SSH with no agent. The scoping guarantee is "only the REQUESTED
	# credentials are added, and no OTHER credential is inherited" — so every
	# credential in the manifest that was NOT requested is unset first, and
	# everything unrelated to credentials is left alone.
	local m
	while IFS= read -r m; do
		unset "$m"
	done < <(all_credential_names)

	local kv
	for kv in "${pairs[@]}"; do
		# Values are assigned, never expanded: `export "$kv"` would re-split a
		# multiline value. Assignment through `export` is a single operation and
		# cannot word-split.
		export "${kv?}"
	done

	exec "${COMMAND[@]}"
}

# ── dispatch ────────────────────────────────────────────────────────────────
n=""
a=""
v=""
if ((${#COMMAND[@]} > 0)); then
	if [[ "$FORMAT" == "nul" ]]; then
		mapfile -t _wanted < <(wanted_names)
		do_exec "${_wanted[@]+"${_wanted[@]}"}"
		exit $?
	fi
	sayf "--exec is only meaningful with --format=nul (the default)."
	exit 2
fi

case "$FORMAT" in
check) collect ${ONLY_NAMES[@]+"${ONLY_NAMES[@]}"}; emit_check; exit $? ;;
json) collect ${ONLY_NAMES[@]+"${ONLY_NAMES[@]}"}; emit_json; exit $? ;;
list) emit_lines; exit 0 ;;
env)
	collect ${ONLY_NAMES[@]+"${ONLY_NAMES[@]}"} || exit 3
	while IFS= read -r n; do
		v="$(read_value "$n")" || exit $?
		while IFS= read -r a; do
			printf '%s=%s\n' "$a" "$v"
		done < <(var_names "$n")
	done < <(wanted_names)
	exit 0
	;;
nul) emit_nul ;;
esac